steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run' ,'test:pact:consumer']
  - name: node
    entrypoint: npm
    args: ['run' ,'test:pact:publish']

